export const MenuActions = [
  { label: 'Edit', value: 'edit' },
  { label: 'Delete', value: 'delete' },
  { label: 'Export', value: 'export' },
]

export const CheckboxValues = [
  { label: 'Checked', value: 'true' },
  { label: 'Unchecked', value: 'false' },
]

export const PageSize = 20

export const ViewTypes = [
  { value: 'shared', label: 'Shared' },
  { value: 'personal', label: 'Personal' },
]

export const OperatorSets = {
  string: [
    { label: 'Contains', value: ':' },
  ],
  dropdown: [
    { label: 'Is', value: ':' },
  ],
  numeric: [
    { label: 'Equals', value: ':' },
    { label: 'Greater than', value: '>' },
    { label: 'Less than', value: '<' },
    { label: 'Greater than or equal to', value: '>=' },
    { label: 'Less than or equal to', value: '<=' },
  ],
  date: [
    { label: 'Greater than', value: '>' },
    { label: 'Less than', value: '<' },
    { label: 'Greater than or equal to', value: '>=' },
    { label: 'Less than or equal to', value: '<=' },
    { label: 'Between', value: '><' },
  ],
  array: [
    { label: 'Contains', value: '[]' },
  ],
  boolean: [
    { label: 'Is', value: ':' },
  ]
}

export const FieldTypes = [
  { type: 'dropdown', operators: OperatorSets.dropdown, input: 'select' },
  { type: 'text', operators: OperatorSets.string, input: 'text' },
  { type: 'textarea', operators: OperatorSets.string, input: 'text' },
  { type: 'regexp', operators: OperatorSets.string, input: 'text' },
  { type: 'decimal', operators: OperatorSets.numeric, input: 'text' },
  { type: 'integer', operators: OperatorSets.numeric, input: 'text' },
  { type: 'checkbox', operators: OperatorSets.boolean, input: 'boolean' },
  { type: 'date', operators: OperatorSets.date, input: 'date' },
  { type: 'list', operators: OperatorSets.array, input: 'tags'  },
  { type: 'lookup', operators: OperatorSets.dropdown, input: 'autocomplete' },
]

export const DefaultOrganizationFields = [
  { title: 'URL', key: 'url', type: 'text' },
  { title: 'ID', key: 'id', type: 'text' },
  { title: 'External ID', key: 'external_id', type: 'text' },
  { title: 'Name', key: 'name', type: 'text' },
  { title: 'Created Date', key: 'created_at', type: 'date' },
  { title: 'Updated Date', key: 'updated_at', type: 'date' },
  { title: 'Domain Names', key: 'domain_names', type: 'list' },
  { title: 'Details', key: 'details', type: 'textarea' },
  { title: 'Notes', key: 'notes', type: 'textarea' },
  { title: 'Group', key: 'group_id', type: 'integer' },
  { title: 'Tags', key: 'tags', type: 'list' },
]

export const TestViews = [
  { id: 'sh1', title: 'Shared 1', type: 'shared' },
  { id: 'sh2', title: 'Shared 2', type: 'shared' },
  { id: 'sh3', title: 'Shared 3', type: 'shared' },
  { id: 'pe1', title: 'Personal 1', type: 'personal' },
  { id: 'pe2', title: 'Personal 2', type: 'personal' },
  { id: 'pe3', title: 'Personal 3', type: 'personal' },
]

export const SampleLookupOptions = [
  {name: 'One', value: 'test_one'},
  {name: 'Two', value: 'test_two'},
  {name: 'Three', value: 'test_three'},
]


export const TestOrgFields = [
  'url',
  'id',
  'name',
  'shared_tickets',
  'shared_comments',
  'external_id',
  'created_at',
  'updated_at',
  'domain_names',
  'details',
  'notes',
  'group_id',
  'tags',
  'organization_fields',
]

export const TestOrganizations = [
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7564869342873.json',
    'id': 7564869342873,
    'name': '11belowbrewing.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-16T19:27:48Z',
    'updated_at': '2022-06-16T19:27:48Z',
    'domain_names': [
      '11belowbrewing.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'q69G2SlQK5ZPK0JpH4ed',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228555974809.json',
    'id': 7228555974809,
    'name': '123jdb@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:10:14Z',
    'updated_at': '2022-06-11T07:06:10Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [
      'csm_louise'
    ],
    'organization_fields': {
      'csapp_id': 'skqDANH27u9uy6n6Lyqq',
      'csm': 'csm_louise',
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7453810310425.json',
    'id': 7453810310425,
    'name': '12dgapsp@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-13T15:18:50Z',
    'updated_at': '2022-06-13T15:18:50Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'OuhPuvZkCuijd7cwA8XZ',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7917697331737.json',
    'id': 7917697331737,
    'name': '12hlmatthews@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-27T17:54:03Z',
    'updated_at': '2022-06-27T17:54:03Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'SpTrrnvM1FTPzmuVYpqs',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228575223577.json',
    'id': 7228575223577,
    'name': '135primex.eu@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:11:49Z',
    'updated_at': '2022-06-06T12:11:49Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'HCjLg3XGIKQzKK6w1ye5',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7881498098457.json',
    'id': 7881498098457,
    'name': '13gp73@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-26T21:38:47Z',
    'updated_at': '2022-06-26T21:38:47Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'H1OOtkfQu9KbLwAXiEpe',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/10669247506329.json',
    'id': 10669247506329,
    'name': '1435n56pp@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-09-20T03:19:28Z',
    'updated_at': '2022-09-20T03:19:28Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [
      'csm_ed'
    ],
    'organization_fields': {
      'csapp_id': 'QdVJuzLLGO3VxCLlWaqH',
      'csm': 'csm_ed',
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7341515089689.json',
    'id': 7341515089689,
    'name': '1654797118.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-09T17:52:17Z',
    'updated_at': '2022-06-09T17:52:17Z',
    'domain_names': [
      '1654797118.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'CiU20SAORzVBrkJy0kjK',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7918988944665.json',
    'id': 7918988944665,
    'name': '1656362849.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-27T20:47:44Z',
    'updated_at': '2022-06-27T20:47:44Z',
    'domain_names': [
      '1656362849.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'KIc8gw7TUOy5tzArWW58',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228373035673.json',
    'id': 7228373035673,
    'name': '1791.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:03:34Z',
    'updated_at': '2022-06-06T12:03:34Z',
    'domain_names': [
      '1791.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'aj1ro2aM4k3GeHwYDq4Y',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228056057497.json',
    'id': 7228056057497,
    'name': '18561644576a@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T11:49:30Z',
    'updated_at': '2022-06-06T11:49:30Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '9sYKdRgAJZFRhQrCZbIT',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7798346064409.json',
    'id': 7798346064409,
    'name': '1991suzukivx800@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-23T17:48:18Z',
    'updated_at': '2022-06-23T17:48:18Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'j1xOx43yWEAss8sbxuMq',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7799065581465.json',
    'id': 7799065581465,
    'name': '19fv88@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-23T19:13:16Z',
    'updated_at': '2022-06-23T19:13:16Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'I4AqlOZUXf2Di6TAp6O7',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7270662141849.json',
    'id': 7270662141849,
    'name': '19ideas.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-07T20:13:56Z',
    'updated_at': '2022-06-07T20:13:56Z',
    'domain_names': [
      '19ideas.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'D4LV6DptxnDkztR53euO',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7925179390233.json',
    'id': 7925179390233,
    'name': '1greathunter@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-28T01:40:11Z',
    'updated_at': '2022-06-28T01:40:11Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'UhBT9LKb2XSMH6je2a80',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228664738713.json',
    'id': 7228664738713,
    'name': '2017vd@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:18:11Z',
    'updated_at': '2022-06-06T12:18:11Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'OG0y1KGqqE9kCAmvnaOZ',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7776209983641.json',
    'id': 7776209983641,
    'name': '247roofingsolutions.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-23T05:28:50Z',
    'updated_at': '2022-06-23T05:28:50Z',
    'domain_names': [
      '247roofingsolutions.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'XAhnB9Qr48LupmexQUIG',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7343597073049.json',
    'id': 7343597073049,
    'name': '2ndtononecreditservices.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-09T22:25:53Z',
    'updated_at': '2022-06-09T22:25:53Z',
    'domain_names': [
      '2ndtononecreditservices.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'Aog6e4s7l6CZA8GCvuW0',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7801086804377.json',
    'id': 7801086804377,
    'name': '2nmeleigh@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-23T23:12:18Z',
    'updated_at': '2022-06-23T23:12:18Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'SQmLW2j6JXu2Kt4qOcFL',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/6642945324057.json',
    'id': 6642945324057,
    'name': '31march3@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-05-16T09:05:04Z',
    'updated_at': '2022-05-16T09:05:04Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'wF1FSIh7M4exoF4Yjpm5',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7689388857113.json',
    'id': 7689388857113,
    'name': '385352@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-21T00:26:40Z',
    'updated_at': '2022-06-21T00:26:40Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'OfnW7z4Nif5yF3J14rS6',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7625113902745.json',
    'id': 7625113902745,
    'name': '3cdigitalmedianetwork.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-18T15:53:21Z',
    'updated_at': '2022-06-18T15:53:21Z',
    'domain_names': [
      '3cdigitalmedianetwork.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'V9dmpPIZTx7eblxswT9I',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7554336772377.json',
    'id': 7554336772377,
    'name': '420lou1234@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-16T09:45:11Z',
    'updated_at': '2022-06-16T09:45:11Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'moHb60Kzq60TzXGBNXX6',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7158040787993.json',
    'id': 7158040787993,
    'name': '4dassociates.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-03T13:25:13Z',
    'updated_at': '2022-06-03T13:25:13Z',
    'domain_names': [
      '4dassociates.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'O4Np9FfthBWkk9AOxqO5',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228149331993.json',
    'id': 7228149331993,
    'name': '4M Express',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T11:53:06Z',
    'updated_at': '2022-06-11T10:00:04Z',
    'domain_names': [
      '4mexpress.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'dmA7iLoBOwCrE20NbpHz',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228205160473.json',
    'id': 7228205160473,
    'name': '4romerofamily@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T11:54:52Z',
    'updated_at': '2022-06-06T11:54:52Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '7zpOI3DBJ30qI9Sys1hu',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228694557465.json',
    'id': 7228694557465,
    'name': '4tekke@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:17:55Z',
    'updated_at': '2022-06-06T12:17:55Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'lpmwSxHxpinaPW31iFdL',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7284096870937.json',
    'id': 7284096870937,
    'name': '4u2nvbish@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-08T04:45:05Z',
    'updated_at': '2022-06-08T04:45:05Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '4iip9nrvmzJYVumAANCQ',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7492571460249.json',
    'id': 7492571460249,
    'name': '7072808+ifax@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-14T21:18:26Z',
    'updated_at': '2022-06-14T21:18:26Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'BAltNirAOdUe3FJt6cZz',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7920453902489.json',
    'id': 7920453902489,
    'name': '77rajwindersidhu@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-27T23:22:47Z',
    'updated_at': '2022-06-27T23:22:47Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '3QyEtk2Y75hHb1XHbgZo',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7626798486937.json',
    'id': 7626798486937,
    'name': '8horserider@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-18T19:06:46Z',
    'updated_at': '2022-06-18T19:06:46Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'Q4gBYXw0Mdj4sZtXruId',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7453181884953.json',
    'id': 7453181884953,
    'name': '916bme@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-13T14:41:36Z',
    'updated_at': '2022-06-13T14:41:36Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '3BtJUGvRd4eKZaka6y4g',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7416229953945.json',
    'id': 7416229953945,
    'name': '9etta.l@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-12T11:01:53Z',
    'updated_at': '2022-06-12T11:01:53Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'C3M6jlU0fXwXLR1FqfYz',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7591434173849.json',
    'id': 7591434173849,
    'name': '?? ????',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-17T10:16:52Z',
    'updated_at': '2022-06-17T10:34:38Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'ZTwYYFQcVRDzruKG97H7',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7908269838873.json',
    'id': 7908269838873,
    'name': 'a-zbus.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-27T09:55:06Z',
    'updated_at': '2022-06-27T09:55:06Z',
    'domain_names': [
      'a-zbus.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'ZvdiNV8LFvavxYZUq6un',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228457190425.json',
    'id': 7228457190425,
    'name': 'a.a.boulifa@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:05:03Z',
    'updated_at': '2022-06-06T12:05:03Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'FrGrHtFjJJzrhLSMhOnV',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7305514224025.json',
    'id': 7305514224025,
    'name': 'a.blekhman@icloud.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-08T18:08:51Z',
    'updated_at': '2022-06-08T18:08:51Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'bZUhhkkGGfH4LgVNgyQZ',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7567922347801.json',
    'id': 7567922347801,
    'name': 'a.chamberlin92@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-17T00:13:12Z',
    'updated_at': '2022-06-17T00:13:12Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'a7KnyBkZ1X3pCi9zI3bO',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7376693816985.json',
    'id': 7376693816985,
    'name': 'a.haygan43@yahoo.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-10T18:56:07Z',
    'updated_at': '2022-06-10T18:56:07Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '4jt8waI8XxCQhLpjYT3D',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228159526425.json',
    'id': 7228159526425,
    'name': 'a.m.dhauw.1101@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T11:54:21Z',
    'updated_at': '2022-06-06T11:54:21Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'qcGhhcljrDE3IG3xBFYI',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7760671775513.json',
    'id': 7760671775513,
    'name': 'aa2gm2025@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-22T19:31:10Z',
    'updated_at': '2022-06-22T19:31:10Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '8NVlAOjzaAKun8FFzXhU',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7455870545433.json',
    'id': 7455870545433,
    'name': 'aacps.org',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-13T18:41:40Z',
    'updated_at': '2022-06-13T18:41:40Z',
    'domain_names': [
      'aacps.org'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'XgNODJ2qSM7bmoUwwCuY',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7268924780953.json',
    'id': 7268924780953,
    'name': 'aamirshekha@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-07T16:41:55Z',
    'updated_at': '2022-06-07T16:41:55Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'O6VEbiNrLDUz3CsqGH2g',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228404339737.json',
    'id': 7228404339737,
    'name': 'aaqilocp@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:04:32Z',
    'updated_at': '2022-06-06T12:04:32Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'yavjKdSP8CNID19gtdv1',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228568257049.json',
    'id': 7228568257049,
    'name': 'Aaron Ash',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:11:55Z',
    'updated_at': '2022-06-06T12:11:55Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'ZukCm279mFWYsCf0gU7j',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7983264037529.json',
    'id': 7983264037529,
    'name': 'aaron.seangsuwan@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-29T10:37:23Z',
    'updated_at': '2022-06-29T10:37:23Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'uh7VX0nQtM7OEze9JHpk',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7402506688537.json',
    'id': 7402506688537,
    'name': 'aaronsullivan623@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-11T23:47:30Z',
    'updated_at': '2022-06-11T23:47:30Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'GFLqQCUgyeO6m8cli95f',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228017207193.json',
    'id': 7228017207193,
    'name': 'ab3iwpayment@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T11:47:47Z',
    'updated_at': '2022-06-06T11:47:47Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'nYDd7wVBB8cr6ictjIgf',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228523845657.json',
    'id': 7228523845657,
    'name': 'ababou.arts@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:10:11Z',
    'updated_at': '2022-06-06T12:10:11Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '3bw6CDMP6MLnviyxkYXo',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228208501529.json',
    'id': 7228208501529,
    'name': 'abana351@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T11:55:50Z',
    'updated_at': '2022-06-06T11:55:50Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'LuMWByydlLEyEqocuzTV',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7468010850201.json',
    'id': 7468010850201,
    'name': 'abarnesmanteca@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-14T04:01:32Z',
    'updated_at': '2022-06-14T04:01:32Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'Gus1S7E5SJAAudVGjoG2',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7491455590041.json',
    'id': 7491455590041,
    'name': 'abbeyegruber@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-14T18:33:41Z',
    'updated_at': '2022-06-14T18:33:41Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'hISpo2fKvgsNR6j8se3K',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7368618270105.json',
    'id': 7368618270105,
    'name': 'AbbyziaLLC@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-10T10:34:54Z',
    'updated_at': '2022-06-10T10:34:54Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'QS0c6M4NgwGR2hT4CtN6',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228515516313.json',
    'id': 7228515516313,
    'name': 'abdallahazawaneh@yahoo.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:09:27Z',
    'updated_at': '2022-06-06T12:09:27Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'YkzlaOCn3OTbqB6kxLHv',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7797755735833.json',
    'id': 7797755735833,
    'name': 'abdellatifdellah1942@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-23T16:50:45Z',
    'updated_at': '2022-06-23T16:50:45Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '3l3tVPvuEnJludn46iNr',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7558987743001.json',
    'id': 7558987743001,
    'name': 'abdulrahim851969@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-16T12:40:51Z',
    'updated_at': '2022-06-16T12:40:51Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'QCbWhTub13PdlZfHvOfm',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7684129132441.json',
    'id': 7684129132441,
    'name': 'abel.c.dutra@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-20T16:33:25Z',
    'updated_at': '2022-06-20T16:33:25Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'Q3AttX6diplagb4jXCR9',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7990905149721.json',
    'id': 7990905149721,
    'name': 'abigaelkathryn.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-29T16:34:00Z',
    'updated_at': '2022-06-29T16:34:00Z',
    'domain_names': [
      'abigaelkathryn.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'RuxULEYAlWagCjgSNWVx',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7646176266393.json',
    'id': 7646176266393,
    'name': 'aboutus1357@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-19T14:15:38Z',
    'updated_at': '2022-06-19T14:15:38Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '5fHUWRP0U8QFZEKVbIVy',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7265579175193.json',
    'id': 7265579175193,
    'name': 'absoluteaircraftsupply.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-07T13:08:33Z',
    'updated_at': '2022-06-07T13:08:33Z',
    'domain_names': [
      'absoluteaircraftsupply.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'V8LUCxohJIQeENvfQHjG',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7236051725977.json',
    'id': 7236051725977,
    'name': 'ac0529@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T23:27:05Z',
    'updated_at': '2022-06-06T23:27:05Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'XVUmaBaGAf0o0fofsmAG',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7529115459865.json',
    'id': 7529115459865,
    'name': 'Acberry3@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-15T21:47:33Z',
    'updated_at': '2022-06-15T21:47:33Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'C9GRkMdGNob6wcJSyrbq',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7227931277721.json',
    'id': 7227931277721,
    'name': 'accessbapsalon@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T11:42:43Z',
    'updated_at': '2022-06-06T11:42:43Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'V34KlWTOW6u4vj883FeD',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/6548947971225.json',
    'id': 6548947971225,
    'name': 'acdfaxln@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-05-12T16:56:51Z',
    'updated_at': '2022-05-12T16:56:51Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'AzbV69YW1UHvYIjDZO95',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7596728108057.json',
    'id': 7596728108057,
    'name': 'acisel@hotmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-17T12:56:12Z',
    'updated_at': '2022-06-17T12:56:12Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'SGC9Hg6QuL2YeY4DZTQ9',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7656019989273.json',
    'id': 7656019989273,
    'name': 'ackbarbabar@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-20T01:56:18Z',
    'updated_at': '2022-06-20T01:56:18Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'DiIhxZZJA4z5kz0W4L5X',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7490716472729.json',
    'id': 7490716472729,
    'name': 'acmico.org',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-14T17:08:53Z',
    'updated_at': '2022-06-14T17:08:53Z',
    'domain_names': [
      'acmico.org'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '9RaAVbgWh4PgQI7vCuht',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7376067289881.json',
    'id': 7376067289881,
    'name': 'acolon6444@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-10T17:30:41Z',
    'updated_at': '2022-06-10T17:30:41Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'hkYrVXTiI2YKAEDn6AAW',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7916864789913.json',
    'id': 7916864789913,
    'name': 'acrpnet.org',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-27T16:29:51Z',
    'updated_at': '2022-06-27T16:29:51Z',
    'domain_names': [
      'acrpnet.org'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'vhV2rnJNpHtjOFIMLbFU',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7954835172889.json',
    'id': 7954835172889,
    'name': 'actionpropertyinvestors@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-28T16:54:32Z',
    'updated_at': '2022-06-28T16:54:32Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'Y0LKLq6Cg8qF6BDMdf2Y',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7831075536793.json',
    'id': 7831075536793,
    'name': 'acucenter@mail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-24T15:10:39Z',
    'updated_at': '2022-06-24T15:10:39Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'RmDCfAzc4MaLH3bzy8HA',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7270779185049.json',
    'id': 7270779185049,
    'name': 'acurity.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-07T20:33:00Z',
    'updated_at': '2022-06-07T20:33:00Z',
    'domain_names': [
      'acurity.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'qETJohPvT9of1edPdYlk',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7186738801049.json',
    'id': 7186738801049,
    'name': 'Adam Harris',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-05T00:05:31Z',
    'updated_at': '2022-06-05T00:05:31Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'AtsLLaZ3yuCZ2Qn55HGJ',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7449574078361.json',
    'id': 7449574078361,
    'name': 'adam.bojko25@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-13T11:49:00Z',
    'updated_at': '2022-06-13T11:49:00Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'hEf5Y9bxcNowzTqKBpuz',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7552787050649.json',
    'id': 7552787050649,
    'name': 'adam.coomber@yahoo.co.uk',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-16T08:59:01Z',
    'updated_at': '2022-06-16T08:59:01Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '2XWwektdwOPPQ3KCbHhr',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7534002415513.json',
    'id': 7534002415513,
    'name': 'adam.perzynski@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-16T01:05:14Z',
    'updated_at': '2022-06-16T01:05:14Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'VWGsTy7ZZOehAp2dh6WK',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7561620378905.json',
    'id': 7561620378905,
    'name': 'adamjoyli@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-16T14:49:33Z',
    'updated_at': '2022-06-16T14:49:33Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'Ws4bF0kkW9aBxhEUHf7C',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7069370220313.json',
    'id': 7069370220313,
    'name': 'adburnslaw.ca',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-05-31T15:07:49Z',
    'updated_at': '2022-05-31T15:07:49Z',
    'domain_names': [
      'adburnslaw.ca'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'o78hS5G6Pu9QQ2i1celm',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7795341771673.json',
    'id': 7795341771673,
    'name': 'adelecrystal@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-23T14:33:24Z',
    'updated_at': '2022-06-23T14:33:24Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'TudFpmrlBugtwRFspuPt',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7702578641561.json',
    'id': 7702578641561,
    'name': 'adelesonnessa@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-21T05:46:04Z',
    'updated_at': '2022-06-21T05:46:04Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'Y1f2vhQsxQHVAqUEmvDo',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7722954091673.json',
    'id': 7722954091673,
    'name': 'adesteve@yahoo.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-21T18:44:35Z',
    'updated_at': '2022-06-21T18:44:35Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'O2M9TOe8zI7ycCZ6ECfQ',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228584889113.json',
    'id': 7228584889113,
    'name': 'adloop.ca',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:13:28Z',
    'updated_at': '2022-06-06T12:13:28Z',
    'domain_names': [
      'adloop.ca'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'RmEEmNjdIpIyWVHx61SC',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7723381089561.json',
    'id': 7723381089561,
    'name': 'adlydavid2@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-21T19:46:28Z',
    'updated_at': '2022-06-21T19:46:28Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'lCk9SJDbgNhew2xDAfla',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/6983060109849.json',
    'id': 6983060109849,
    'name': 'adm.mayser@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-05-28T10:02:23Z',
    'updated_at': '2022-05-28T10:02:23Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'dFlBw7gjkWqHcuSxakkS',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7341862636441.json',
    'id': 7341862636441,
    'name': 'adolbashian@ymail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-09T18:28:05Z',
    'updated_at': '2022-06-09T18:28:05Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'h9FPOGy6c4ooSGHp4XHB',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7974756482713.json',
    'id': 7974756482713,
    'name': 'adom kabol',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-29T06:49:22Z',
    'updated_at': '2022-06-29T06:49:22Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'APjTbMpJhHYusqnZaJvy',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7954169643417.json',
    'id': 7954169643417,
    'name': 'adorama.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-28T16:01:02Z',
    'updated_at': '2022-06-28T16:01:02Z',
    'domain_names': [
      'adorama.com'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'XUFJBiBLRuPLgnOZCJOS',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7915538904601.json',
    'id': 7915538904601,
    'name': 'adri.zambrano.solines@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-27T15:00:08Z',
    'updated_at': '2022-06-27T15:00:08Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'vCvhURbYgQdUOhHGe3wz',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228707969561.json',
    'id': 7228707969561,
    'name': 'adriaanjohanneslouw51@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:17:11Z',
    'updated_at': '2022-06-06T12:17:11Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'Vh2E1rIW4dZqeFiCYmDY',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7954130559001.json',
    'id': 7954130559001,
    'name': 'Adrian Bart',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-28T15:57:52Z',
    'updated_at': '2022-06-28T15:57:52Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'wbq54SEk1yhKb1kvuRBn',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228127073433.json',
    'id': 7228127073433,
    'name': 'adrian24132@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T11:52:44Z',
    'updated_at': '2022-06-06T11:52:44Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '9lmVHLUleozDnwsTj7Y0',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7598539847961.json',
    'id': 7598539847961,
    'name': 'adrianna69911@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-17T14:14:32Z',
    'updated_at': '2022-06-17T14:14:31Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'fBUYdhQAUGHerxLUSQdl',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228575795353.json',
    'id': 7228575795353,
    'name': 'adv.shthakore@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T12:11:58Z',
    'updated_at': '2022-06-06T12:11:58Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'hYv7wF5f23bY9sYVUYII',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7374026591129.json',
    'id': 7374026591129,
    'name': 'advo.email',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-10T14:37:04Z',
    'updated_at': '2022-06-10T14:37:09Z',
    'domain_names': [
      'advo.email'
    ],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [
      'csm_rollie'
    ],
    'organization_fields': {
      'csapp_id': 'bDWXhRhGnOUcxNCLygVr',
      'csm': 'csm_rollie',
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7522171208985.json',
    'id': 7522171208985,
    'name': 'aedin.wellnessnyc@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-15T12:50:27Z',
    'updated_at': '2022-06-15T12:50:27Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'IH5q03A4EkLsmR6SOj54',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7228050191641.json',
    'id': 7228050191641,
    'name': 'aerussell2014@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-06T11:49:31Z',
    'updated_at': '2022-06-06T11:49:31Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'YMndowXRcA8KTchwLvDF',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7792418010521.json',
    'id': 7792418010521,
    'name': 'aetaklif@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-23T12:57:38Z',
    'updated_at': '2022-06-23T12:57:38Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'XAa4VvDiMZZHqq5RJZ2C',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7455876670105.json',
    'id': 7455876670105,
    'name': 'aezambrano@yahoo.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-13T18:47:33Z',
    'updated_at': '2022-06-13T18:47:33Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '1CN8XLdaKvr2m9P785an',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7724152665881.json',
    'id': 7724152665881,
    'name': 'afghans998@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-21T21:25:20Z',
    'updated_at': '2022-06-21T21:25:19Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': '33sEVfBhoAdeO2NTjyhi',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  },
  {
    'url': 'https://d3v-getassist.zendesk.com/api/v2/organizations/7723258644761.json',
    'id': 7723258644761,
    'name': 'agarver00@gmail.com',
    'shared_tickets': false,
    'shared_comments': false,
    'external_id': null,
    'created_at': '2022-06-21T19:20:54Z',
    'updated_at': '2022-06-21T19:20:54Z',
    'domain_names': [],
    'details': null,
    'notes': null,
    'group_id': null,
    'tags': [],
    'organization_fields': {
      'csapp_id': 'Hrq5oaZcdJMvj0y3lysS',
      'csm': null,
      'subscription_end_date': null,
      'subscription_start_date': null,
      'subscription_status': null,
      'support_plan': null
    }
  }
]